services:
  graphdb:
    image: ontotext/graphdb:11.3.3
    container_name: graphdb

    ports:
      - 7200:7200

    volumes:
      - ./data-docker/graphdb/data:/opt/graphdb/home
      - ./data-docker/graphdb/notebooks:/notebooks
      - ./graphdb-init/GRAPHDB_FREE_v11.3.license:/opt/graphdb/dist/conf/graphdb.license

    environment:
      graphdb.license.file: /opt/graphdb/dist/conf/graphdb.license

  graphdb-init:
    image: curlimages/curl:latest

    depends_on:
      - graphdb

    volumes:
      - ./graphdb-init:/init
      - ../src/rdf_conversion/output:/rdf

    entrypoint: ["/bin/sh", "/init/init.sh"]
    