name: cicd
run-name: ${{ github.actor }} is generating ontology file
on:
  push:
    branches:
      - feature/*
      - release/*

permissions:
  contents: write
  actions: write

jobs:
    build-ontology:
        runs-on: ubuntu-24.04
        steps:
          - name: Checkout source
            uses: actions/checkout@v4
            with:
                token: ${{ secrets.PAT_TOKEN }}
                fetch-depth: 0
                lfs: true

          - name: Set up Python 3.12
            uses: actions/setup-python@v4
            with:
                python-version: '3.12'
      
          - name: Verify Python Installation
            run: python --version
      
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install -e .
  
          - name: Generate ontology file
            run: |
                python -m src.rdf_conversion.main

          - name: Set up Java
            uses: actions/setup-java@v4
            with:
                distribution: 'temurin'
                java-version: '17'

          # https://robot.obolibrary.org/
          - name: Download Robot
            run: |
                curl -L -o robot.jar https://github.com/ontodev/robot/releases/latest/download/robot.jar

          - name: Validate ontology
            run: |
                sed '/owl:imports/d' src/rdf_conversion/output/ontometal.ttl > src/rdf_conversion/output/ontometal_no_imports.ttl
                java -Xmx4g -jar robot.jar reason --reasoner HermiT --input src/rdf_conversion/output/ontometal_no_imports.ttl
                rm src/rdf_conversion/output/ontometal_no_imports.ttl
  
          - name: Commit and push ontology file
            run: |
                git config user.name 'OceanBerlinghieri'
                git config user.email 'OceanBerlinghieri@users.noreply.github.com'
                git add --all
                if ! git diff --cached --quiet; then
                    git commit -m 'Update ontology file [skip ci]'
                    git push origin HEAD
                else
                    echo 'No ontology file changes to commit.'
                fi
